apiVersion: v1
kind: Service
metadata:
  name: devdocs
  namespace: devdocs
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port:
      targetPort:
      nodePort:
  selector:
    app: devdocs
